### PR TITLE
Gathered various update

### PR DESCRIPTION
**Pull request by couin3**
Hi,
I've read all RFM69OOK forks and gathered all the changes.
It can be interesting to merge them!
Regards

### CODE REVIEW

**Comment by kobuki** [comment]
@couin3 thanks for your work. Additions, fixes, suggestions are always welcome. But please keep in mind that this repo is meant for simplicity and a groundwork for more complex or advanced things. For instance, functions for analyzing, capturing, interpreting data belong to user sketches, not the library. I don't yet know what the changes entail, just noting it for now. Give me a few days to review the changes.

**Comment by kobuki** [comment]
Alright, I glanced over all the commits. I'm willing to merge changes that add support for more devices. The following commits don't make sense in the base lib:

maroprjs : Manual Reset -- Out of context, I don't even know what it resets.

cwhinton : OPMODE -> bit sequencer enabled This is the recommended default in the RFM69HCW data sheet. -- Makes no sense. We're basically sampling the OOK carrier with arbitrary timings. The sequencer gathers bits in the module's FIFO buffer with set timing, checks for sync word, etc, but we don't use this facility at all.

I'll reject the pull as is, but will look into the device support commits later. They would be useful additions.

**Comment by couin3** [comment]
maroprjs : Manual Reset -- Out of context, I don't even know what it resets.
It resets RFM69, using its RST pin, hence "manual" reset.

**Comment by couin3** [comment]
cwhinton : OPMODE -> bit sequencer enabled
I'm just starting to dig in RFM69 datasheet, and I was myself not sure about this one.
As I quote, it's a copy of cwhinton repository.

**Comment by kobuki** [comment]
> maroprjs : Manual Reset -- Out of context, I don't even know what it resets.
> It resets RFM69, using its RST pin, hence "manual" reset.

It's module/maker specific. Toggling arbitrary bits for module reset for any specific target board can be done in user code.

**Comment by couin3** [comment]
RF69OOK_IRQ_PIN, (RF69OOK_IRQ_NUM), RF69OOK_SPI_CS are also module specific !
RST_PIN is not even connected on MOTEINO board.
But I wish this library to be more generic, yet still MOTEINO friendly.
That's why having a well integrated reset chip capabilities would have been a plus.

**Comment by kobuki** [comment]
The lib was originally made for Moteinos. Most don't even have reset connected to a GPIO. If you convince me that reset functionality is needed for OOK operation, I'm willing to consider adding it with a generalized config for other boards.

**Comment by couin3** [comment]
If you wish, I will ask maroprjs why he specifically added this "Manual" Reset in its fork. 
I guess apart Moteino/ATmega328p, startup sequence can be more messy, and a hardware Reset is welcome.
On most LoRaWan Board (RFM9x series), RST pins is connected and library has at least to set pin state (LOW / HIGH / Float)

**Comment by kobuki** [comment]
> If you wish, I will ask maroprjs why he specifically added this "Manual" Reset in its fork.

Thanks, that could be useful. RFM69xx modules are quite stable, they either work without regular resets or they don't work at all, usually DOA. The initial reset at MCU boot should suffice. At the moment, other modules like RFM95/96 are not supported by this driver, although they do support OOK and might need special handling and reset ability.

**Pull request closed without merging**
